### ISSUE TITLE
Make code editor respect Burp's configured font size

### ISSUE THREAD

**Issue by lnxdork** [hackvertor/hackvertor#50]
I have set the font options in burp to work well with a 4k monitor.
The code displayed in the hackvertor panels does not display using the font sizes set in burp.
![hackvertor](https://user-images.githubusercontent.com/40716638/119585036-dec38900-bd97-11eb-8a60-df51079ad67c.png)

**Comment by hackvertor** [comment]
This has now been fixed and will be in the next release. When you change your font setting you'll have to reload the extension in order to get the correct size. The reason for this is I want to ensure I use a fixed width font and if I use the customiseUIComponent in the Burp API this will also change the font.
