### ISSUE TITLE
Getting the loop number

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#91]
I want to generate a value like this "1,2,3,4,5..." and I thought I should use a Loop variable but I cannot access the counter in:
```
<@loop_for(0,49,1,'i')>test<@/loop_for>
```
IS there any way to access `i` or is there any better way to what I want to do with HV default tags without coding it myself?

**Comment by hackvertor** [comment]
This is a bug. There's no current way of doing this. Since the move to the better parser which goes inside out, loop tags need to go outside in which the current parser doesn't support. The loop tags are going to be removed in future. Sorry about that, you can use a custom tag as a workaround cheers

**Comment by hackvertor** [comment]
This has been replaced by increment/decrement tags and the loop tags have been removed
